### ISSUE TITLE
error with Julia 0.5

### ISSUE THREAD

**Issue by jingpengwu** [stevengj/PyCall.jl#254]
everything works in Julia 0.4, but when I switch to Julia 0.5. all the python part can not be used because of malfunction of PyCall.

ubuntu 14.10
```
using PyCall

signal (11): Segmentation fault
while loading no file, in expression starting on line 0
PyObject_Call at -------src-dir-------/Python-2.7.10/Objects/abstract.c:2525
[inline] at /usr/people/jingpeng/.julia/v0.5/PyCall/src/exception.jl:79
pycall at /usr/people/jingpeng/.julia/v0.5/PyCall/src/PyCall.jl:356
[inline] at /usr/people/jingpeng/workspace/julia/src/julia_internal.h:69
jl_call_method_internal at /usr/people/jingpeng/workspace/julia/src/gf.c:1872
jl_f__apply at /usr/people/jingpeng/workspace/julia/src/builtins.c:506
unknown function (ip: 0x7f04fd78b566)
show at /usr/people/jingpeng/.julia/v0.5/PyCall/src/exception.jl:39
showerror at ./replutil.jl:100
unknown function (ip: 0x7f04fd78b1aa)
[inline] at /usr/people/jingpeng/workspace/julia/src/julia_internal.h:69
jl_call_method_internal at /usr/people/jingpeng/workspace/julia/src/gf.c:1872
unknown function (ip: 0x7f04fd80e1e3)
unknown function (ip: 0x7f04fd80e373)
[inline] at /usr/people/jingpeng/workspace/julia/src/julia_internal.h:69
jl_call_method_internal at /usr/people/jingpeng/workspace/julia/src/gf.c:1872
showerror at ./replutil.jl:116
#3 at ./REPL.jl:101
unknown function (ip: 0x7f04fd84a0c3)
[inline] at /usr/people/jingpeng/workspace/julia/src/julia_internal.h:69
jl_call_method_internal at /usr/people/jingpeng/workspace/julia/src/gf.c:1872
with_output_color at ./util.jl:317
[inline] at /usr/people/jingpeng/workspace/julia/src/julia_internal.h:69
jl_call_method_internal at /usr/people/jingpeng/workspace/julia/src/gf.c:1872
[inline] at ./char.jl:51
print_response at ./REPL.jl:128
unknown function (ip: 0x7f04fdb512ce)
[inline] at /usr/people/jingpeng/workspace/julia/src/julia_internal.h:69
jl_call_method_internal at /usr/people/jingpeng/workspace/julia/src/gf.c:1872
print_response at ./REPL.jl:121
unknown function (ip: 0x7f04fdb530de)
[inline] at /usr/people/jingpeng/workspace/julia/src/julia_internal.h:69
jl_call_method_internal at /usr/people/jingpeng/workspace/julia/src/gf.c:1872
#18 at ./REPL.jl:628
unknown function (ip: 0x7f071dbe878f)
[inline] at /usr/people/jingpeng/workspace/julia/src/julia_internal.h:69
jl_call_method_internal at /usr/people/jingpeng/workspace/julia/src/gf.c:1872
run_interface at ./LineEdit.jl:1563
unknown function (ip: 0x7f07184da0a0)
[inline] at /usr/people/jingpeng/workspace/julia/src/julia_internal.h:69
jl_call_method_internal at /usr/people/jingpeng/workspace/julia/src/gf.c:1872
run_frontend at ./REPL.jl:875
run_repl at ./REPL.jl:167
unknown function (ip: 0x7f071dc4e194)
[inline] at /usr/people/jingpeng/workspace/julia/src/julia_internal.h:69
jl_call_method_internal at /usr/people/jingpeng/workspace/julia/src/gf.c:1872
_start at ./client.jl:360
unknown function (ip: 0x7f07185085e2)
[inline] at /usr/people/jingpeng/workspace/julia/src/julia_internal.h:69
jl_call_method_internal at /usr/people/jingpeng/workspace/julia/src/gf.c:1872
unknown function (ip: 0x401b13)
unknown function (ip: 0x4016df)
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
Allocations: 13200394 (Pool: 13195577; Big: 4817); GC: 27
Segmentation fault

```

**Comment by stevengj** [comment]
I think this is due to the problem described in JuliaLang/julia#15300.   @yuyichao, @vtjnash, is there an open Julia issue to track this problem?

**Comment by stevengj** [comment]
Or was that fixed by JuliaLang/julia#15556?

**Comment by yuyichao** [comment]
The problem mentioned in JuliaLang/julia#15300 should already be fixed and have a different symptom. What is the `versioninfo()` ? `PyCall` works for me on three days old master `0.5.0-dev+3385`.

**Comment by stevengj** [comment]
(I wonder if these problems are related to my usage of `global const foo = ...` in `__init__`.   I get the impression that this construct is discouraged?   But if it doesn't work in 0.5, it would be good to give an actual error.)

**Comment by yuyichao** [comment]
It is discouraged since it will not help type inference on precompiled method that uses the variable. There is an issue for this already.

**Comment by stevengj** [comment]
I just built the latest Julia `master` on MacOS X, and PyCall builds successfully, though there is a test failure on `length(collect(((pyimport("itertools"))[:combinations])([1,2,3],2))) == 3` that I need to track down.

**Comment by perrinmeyer** [comment]
PyPlot and PyCall have been broken on my Samsung chrome2 arm ubuntu crouton for a while now.

I got a "Fixed by #1556" message, but i just rebuild from master (make clean ; make -j 4) and I still get the PyCall llvm error

thanks

perrin


(trusty)perrin@localhost:/home/psmsd/julia_builds/julia$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-dev+3426 (2016-04-06 17:13 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 61f2d2b (0 days old master)
|__/                   |  arm-linux-gnueabihf

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Computing changes...
INFO: No packages to install, update or remove

julia> Pkg.build("PyPlot")
INFO: Building PyCall
INFO: Recompiling stale cache file /home/perrin/.julia/lib/v0.5/Compat.ji for module Compat.
INFO: Recompiling stale cache file /home/perrin/.julia/lib/v0.5/Conda.ji for module Conda.
INFO: Recompiling stale cache file /home/perrin/.julia/lib/v0.5/JSON.ji for module JSON.
INFO: Recompiling stale cache file /home/perrin/.julia/lib/v0.5/BinDeps.ji for module BinDeps.
INFO: Recompiling stale cache file /home/perrin/.julia/lib/v0.5/URIParser.ji for module URIParser.
INFO: Recompiling stale cache file /home/perrin/.julia/lib/v0.5/SHA.ji for module SHA.
WARNING: readall is deprecated, use readstring instead.
while loading /home/perrin/.julia/v0.5/PyCall/deps/build.jl, in expression starting on line 17
WARNING: readall is deprecated, use readstring instead.
while loading /home/perrin/.julia/v0.5/PyCall/deps/build.jl, in expression starting on line 17
WARNING: readall is deprecated, use readstring instead.
while loading /home/perrin/.julia/v0.5/PyCall/deps/build.jl, in expression starting on line 17
WARNING: readall is deprecated, use readstring instead.
while loading /home/perrin/.julia/v0.5/PyCall/deps/build.jl, in expression starting on line 17
WARNING: readall is deprecated, use readstring instead.
while loading /home/perrin/.julia/v0.5/PyCall/deps/build.jl, in expression starting on line 17
WARNING: readall is deprecated, use readstring instead.
while loading /home/perrin/.julia/v0.5/PyCall/deps/build.jl, in expression starting on line 17
WARNING: readall is deprecated, use readstring instead.
while loading /home/perrin/.julia/v0.5/PyCall/deps/build.jl, in expression starting on line 17
WARNING: readall is deprecated, use readstring instead.
while loading /home/perrin/.julia/v0.5/PyCall/deps/build.jl, in expression starting on line 17
WARNING: readall is deprecated, use readstring instead.
while loading /home/perrin/.julia/v0.5/PyCall/deps/build.jl, in expression starting on line 17
INFO: PyCall is using /usr/bin/python (Python 2.7.6) at /usr/bin/python, libpython = libpython2.7

julia> using PyPlot
INFO: Precompiling module PyPlot...
julia: /home/psmsd/julia_builds/julia/src/ccall.cpp:160: llvm::Value* llvm_type_rewrite(llvm::Value*, llvm::Type*, llvm::Type*, bool, bool, bool, jl_codectx_t*): Assertion `from_type->isPointerTy() == target_type->isPointerTy()' failed.
ERROR: LoadError: Failed to precompile PyCall to /home/perrin/.julia/lib/v0.5/PyCall.ji
while loading /home/perrin/.julia/v0.5/PyPlot/src/PyPlot.jl, in expression starting on line 5
ERROR: Failed to precompile PyPlot to /home/perrin/.julia/lib/v0.5/PyPlot.ji

julia>

**Comment by perrinmeyer** [comment]
sorry, there appears to be a julia bug for the LLVM / arm issue (related?)

https://github.com/JuliaLang/julia/issues/15432

perrin

**Comment by stevengj** [comment]
The ARM issues seem unrelated to the problem that @jingpengwu is seeing.

**Comment by stevengj** [comment]
Is this still an issue?  I've been using PyCall successfully with Julia 0.5 for a while now...

**Comment by yuyichao** [comment]
On May 23, 2016 10:33 PM, "Steven G. Johnson" <notifications@github.com>
wrote:
>
> Is this still an issue? I've been using PyCall successfully with Julia
0.5 for a while now...

Should be fixed now.

**Comment by perrinmeyer** [comment]
I recently built 0.4.6pre on my arm crouton chromebook and the backported arm patches fixed pycall and pyplot works which is really awesome thanks!

perrin (poorly finger typing)
415 471 0136
 
 
  On Mon, May 23, 2016 at 7:33 PM, Steven G. Johnson<notifications@github.com> wrote:   
Is this still an issue? I've been using PyCall successfully with Julia 0.5 for a while now...
